# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-24 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('U_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_id', models.CharField(max_length=14)),
                ('user_name', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=20)),
                ('apply_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
