# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-24 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('C_id', models.AutoField(primary_key=True, serialize=False)),
                ('U_id', models.IntegerField()),
                ('Q_id', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Q_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option_A', models.TextField()),
                ('option_B', models.TextField()),
                ('option_C', models.TextField()),
                ('option_D', models.TextField()),
                ('q_key', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('V_id', models.AutoField(primary_key=True, serialize=False)),
                ('U_id', models.IntegerField()),
                ('Q_id', models.IntegerField()),
            ],
        ),
    ]
