# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-28 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_collection_question_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Q_subject',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
