# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-30 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=8)),
                ('title', models.TextField(max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('count', models.CharField(max_length=5)),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=20)),
                ('title', models.TextField(max_length=200)),
                ('count', models.CharField(max_length=5)),
                ('result', models.CharField(max_length=60)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
